---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  tasks:
  - name: debuging
    debug:
      msg: "https://gitlab.com/api/v4/projects/{{ project_id }}/pipelines?per_page=100&sort=asc&updated_before={{ updated_before }}"

  - name: get pipeline list
    uri: 
      url: https://gitlab.com/api/v4/projects/{{ project_id }}/pipelines?per_page=100&sort=asc&updated_before={{ updated_before }}
      method: GET
      headers:
        PRIVATE-TOKEN: "{{ private_token }}"
    register: _result

  # - name: debug _result
  #   debug: var=_result

  # - name: loop _result
  #   debug: 
  #     msg: "pipelineID >> {{ item.id }}"
  #   loop: "{{ _result.json }}"

  - name: delete pipeline by id
    uri:
      url: https://gitlab.com/api/v4/projects/{{ project_id }}/pipelines/{{ item.id }}
      method: DELETE
      headers:
        PRIVATE-TOKEN: "{{ private_token }}"
      status_code: 204
    loop: "{{ _result.json }}"